### ISSUE TITLE
update g20210505 to g20210523 make does not do anything

### ISSUE THREAD

**Issue by dml33** [huo-ju/photoprism-freebsd-port#19]
Hi.

I have my photoprism g20210505 totally compiled and I wanted to update it to g20210523.

In my photoprism-freebsd-port folder, I did a `git pull` to update the repo. Thus, several packages were updated. Then, I did a `make configure` to be sure everything was fine. Then, I typed `make`, but it did not do absolutely anything. It did not download the new g20210523 version or compile it.

I had to `git clone https://github.com/huo-ju/photoprism-freebsd-port` again to a new folder. But, doing this, it also downloaded again tensorflow 1.15.2 and began again its compilation...

Could be possible just to download and compile the photoprism itself, since the tensorflow version has not changed this time?

Thanks!

**Comment by huo-ju** [comment]
Yes, I agree it should be improved, but it's a little complicated because the original build script must be rewritten. I'm working on it, but need more time to finish.

**Comment by psa** [comment]
Part of the problem is that the ports tree isn't really designed for building multiple things like this. `make clean; make package` should rebuild it properly but at the moment it's going to rebuild tensorflow. 

Ultimately, we need to help the `science/py-tensorflow` package get fixed (which will be a challenge given bazel and its tendency to suck things from the internet). 

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=250646 for anyone who wants to put some time into helping out py-tensorflow.
